<?php

namespace App\Service;

use App\Dto\GamerPerformanceDto;
use App\Entity\SteamStats;

class Cs2StatsService
{
    public function calculateFromEntity(SteamStats $stats): GamerPerformanceDto
    {
        $matches = $stats->getTotalMatches() ?? 0;
        if ($matches === 0) {
            return $this->createEmptyDto('cs2');
        }

        $winRate = $stats->getWinRate() ?? 0;
        $kdRatio = $stats->getKdRatio() ?? 0;
        $hsPercent = $stats->getHeadshotPercentage() ?? 0;

        $performanceIndicator = $this->determineIndicator($winRate, $kdRatio, $hsPercent);

        return new GamerPerformanceDto(
            game: 'cs2',
            matchCount: $matches,
            wins: $stats->getWins() ?? 0,
            losses: $stats->getLosses() ?? 0,
            winRate: round($winRate, 1),
            avgKills: $matches > 0 ? round($stats->getKills() / $matches, 1) : 0,
            avgDeaths: $matches > 0 ? round($stats->getDeaths() / $matches, 1) : 0,
            avgAssists: $matches > 0 ? round($stats->getAssists() / $matches, 1) : 0,
            avgKda: round($kdRatio, 2),
            mostPlayed: ['name' => 'CS2 Player', 'games' => $matches, 'winRate' => $winRate],
            performanceIndicator: $performanceIndicator,
            scoutingSummary: '', // Generated by orchestrator
            advancedMetrics: [
                'hsPercent' => round($hsPercent, 1),
                'totalKills' => $stats->getKills() ?? 0,
                'totalDeaths' => $stats->getDeaths() ?? 0,
                'avgHs' => round($hsPercent, 1), // Using for impact calc in template if needed
            ],
            recentMatches: [] // Steam doesn't provide easy match history
        );
    }

    private function determineIndicator(float $winRate, float $kd, float $hs): string
    {
        if ($winRate >= 58 && $kd >= 1.4)
            return 'Elite';
        if ($winRate >= 52 || $kd >= 1.1)
            return 'Strong';
        if ($winRate >= 46)
            return 'Developing';
        return 'Inconsistent';
    }

    private function createEmptyDto(string $game): GamerPerformanceDto
    {
        return new GamerPerformanceDto(
            $game,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            ['name' => 'N/A', 'games' => 0, 'winRate' => 0],
            'N/A',
            'Insufficient data to generate a scouting report.'
        );
    }
}
