<?php

namespace App\Service;

use App\Dto\GamerPerformanceDto;

class LeagueStatsService
{
    /**
     * @param array<int, array<string, mixed>> $matches
     * @param array<string, mixed> $rankData
     */
    /**
     * @param array<int, array<string, mixed>> $matches
     * @param array<string, mixed> $rankData
     */
    /**
     * @param array<int, array<string, mixed>> $matches
     * @param array<string, mixed> $rankData
     */
    public function calculate(array $matches, array $rankData = []): GamerPerformanceDto
    {
        $count = count($matches);
        if ($count === 0) {
            return $this->createEmptyDto('lol');
        }

        $wins = 0;
        $kills = 0;
        $deaths = 0;
        $assists = 0;
        $totalCs = 0;
        $totalGold = 0;
        $totalVision = 0;
        $totalDamage = 0;
        $champions = [];

        foreach ($matches as $m) {
            if ($m['win'])
                $wins++;
            $kills += $m['kills'] ?? 0;
            $deaths += $m['deaths'] ?? 0;
            $assists += $m['assists'] ?? 0;
            $totalCs += $m['csPerMin'] ?? 0;
            $totalGold += $m['goldPerMin'] ?? 0;
            $totalVision += $m['visionScore'] ?? 0;
            $totalDamage += $m['totalDamage'] ?? 0;

            $champ = $m['championName'] ?? 'Unknown';
            if (!isset($champions[$champ])) {
                $champions[$champ] = ['games' => 0, 'wins' => 0];
            }
            $champions[$champ]['games']++;
            if ($m['win'])
                $champions[$champ]['wins']++;
        }

        $winRate = ($wins / $count) * 100;
        $avgKda = ($kills + $assists) / max(1, $deaths);

        uasort($champions, fn($a, $b) => $b['games'] <=> $a['games']);
        $mostPlayedChamp = array_key_first($champions);
        $mostPlayedData = [
            'name' => $mostPlayedChamp,
            'games' => $champions[$mostPlayedChamp]['games'],
            'winRate' => ($champions[$mostPlayedChamp]['wins'] / $champions[$mostPlayedChamp]['games']) * 100
        ];

        $performanceIndicator = $this->determineIndicator($winRate, $avgKda);

        return new GamerPerformanceDto(
            game: 'lol',
            matchCount: $count,
            wins: $wins,
            losses: $count - $wins,
            winRate: round($winRate, 1),
            avgKills: round($kills / $count, 1),
            avgDeaths: round($deaths / $count, 1),
            avgAssists: round($assists / $count, 1),
            avgKda: round($avgKda, 2),
            mostPlayed: $mostPlayedData,
            performanceIndicator: $performanceIndicator,
            scoutingSummary: '', // Will be generated by orchestrator or dedicated helper
            advancedMetrics: [
                'avgCsMin' => round($totalCs / $count, 1),
                'avgGoldMin' => round($totalGold / $count),
                'avgVision' => round($totalVision / $count, 1),
                'avgDamage' => round($totalDamage / $count),
            ]
        );
    }

    private function determineIndicator(float $winRate, float $kda): string
    {
        if ($winRate >= 60 && $kda >= 4)
            return 'Elite';
        if ($winRate >= 52 || $kda >= 3)
            return 'Strong';
        if ($winRate >= 48)
            return 'Developing';
        return 'Inconsistent';
    }

    private function createEmptyDto(string $game): GamerPerformanceDto
    {
        return new GamerPerformanceDto(
            $game,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            ['name' => 'N/A', 'games' => 0, 'winRate' => 0],
            'N/A',
            'Insufficient data to generate a scouting report.'
        );
    }
}
